# Generated by Django 3.2.8 on 2021-11-23 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('WD', 'Wuthdraw'), ('RF', 'Refill')], max_length=2, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Сумма операции в рублях')),
                ('stamp', models.DateTimeField(verbose_name='Дата/время операции')),
            ],
            options={
                'verbose_name': 'Операция по балансу',
                'verbose_name_plural': 'Операции по балансу',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IS', 'Issued'), ('BO', 'Bought'), ('US', 'Used')], max_length=2, verbose_name='Текущий статус сертификата')),
                ('number', models.CharField(max_length=10, verbose_name='Номер сертификата')),
                ('nominal', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Номинал сертификата в рублях')),
                ('issued_stamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время выпуска сертификата')),
                ('acquisition_stamp', models.DateTimeField(verbose_name='Дата/время приобретения сертификата')),
                ('usage_stamp', models.DateTimeField(verbose_name='Дата/время использования сертификата')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='SkydivingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название услуги')),
                ('price', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Стоимость услуги в рублях')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AlterModelOptions(
            name='skydiver',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterUniqueTogether(
            name='skydiver',
            unique_together={('last_name', 'first_name', 'patronymic', 'passport_number')},
        ),
        migrations.CreateModel(
            name='WithdrawalBalanceOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manifest.balanceoperation')),
                ('services', models.ManyToManyField(to='manifest.SkydivingService')),
            ],
            options={
                'verbose_name': 'Операция cписания за услуги',
                'verbose_name_plural': 'Операции cписания за услуги',
            },
        ),
        migrations.CreateModel(
            name='CertificateBalanceOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manifest.certificate')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manifest.balanceoperation')),
            ],
            options={
                'verbose_name': 'Операция c сертификатом',
                'verbose_name_plural': 'Операции c сертификатом',
            },
        ),
        migrations.AddField(
            model_name='balanceoperation',
            name='skydiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manifest.skydiver'),
        ),
    ]
