# Generated by Django 3.2.8 on 2021-11-28 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0003_rename_certificate_giftcertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=10, verbose_name='Регистрационный номер воздушного судна')),
                ('capacity', models.SmallIntegerField(verbose_name='Вместительность')),
            ],
            options={
                'verbose_name': 'Воздушное судно',
                'verbose_name_plural': 'Воздушные судна',
            },
        ),
        migrations.CreateModel(
            name='PlaneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название типа воздушного судна')),
                ('default_capacity', models.SmallIntegerField(verbose_name='Вместительность по умолчанию')),
            ],
            options={
                'verbose_name': 'Тип воздушного судна',
                'verbose_name_plural': 'Типы воздушных суден',
            },
        ),
        migrations.AlterField(
            model_name='balanceoperation',
            name='operation_type',
            field=models.CharField(choices=[('WD', 'Withdraw'), ('RF', 'Refill')], max_length=2, verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='balanceoperation',
            name='skydiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manifest.skydiver', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='certificatebalanceoperation',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manifest.giftcertificate', verbose_name='Сертификат'),
        ),
        migrations.AlterField(
            model_name='certificatebalanceoperation',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manifest.balanceoperation', verbose_name='Операция'),
        ),
        migrations.CreateModel(
            name='SkydiverRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationStamp', models.DateTimeField(verbose_name='Дата/время создания заявки')),
                ('status', models.CharField(choices=[('CR', 'Created'), ('CMP', 'Completed')], max_length=3, verbose_name='Текущий статус заявки')),
                ('services', models.ManyToManyField(to='manifest.SkydivingService', verbose_name='Услуги в заявке')),
                ('skydiver', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manifest.skydiver', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='PlaneLift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Дата подъема')),
                ('ord_numver', models.SmallIntegerField(verbose_name='Порядковый номер')),
                ('status', models.CharField(choices=[('CR', 'Created'), ('PL', 'Planned'), ('FRM', 'Formed'), ('RD', 'Ready to take-off'), ('IP', 'In progress'), ('CMP', 'Completed'), ('CNC', 'Canceled')], max_length=3, verbose_name='Текущий статус подъема')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manifest.plane', verbose_name='Воздушное судно')),
                ('requests', models.ManyToManyField(to='manifest.SkydiverRequest', verbose_name='Заявки в подъеме')),
            ],
            options={
                'verbose_name': 'Подъем воздушного судна',
                'verbose_name_plural': 'Подъемы воздушных суден',
            },
        ),
        migrations.AddField(
            model_name='plane',
            name='plane_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='manifest.planetype', verbose_name='Тип воздушного судна'),
        ),
    ]
