# Generated by Django 3.2.8 on 2021-11-28 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0004_auto_20211128_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkydiveDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название дисциплины')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.AddField(
            model_name='skydiver',
            name='weight',
            field=models.FloatField(blank=True, default=75, verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='skydiverrequest',
            name='height',
            field=models.FloatField(default=1200, verbose_name='Высота прыжка'),
        ),
        migrations.AddField(
            model_name='skydiverrequest',
            name='discipline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='manifest.skydivediscipline', verbose_name='Клиент'),
        ),
    ]
