# Generated by Django 3.2.8 on 2021-12-01 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0007_alter_skydivediscipline_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skydiverrequest',
            name='discipline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='manifest.skydivediscipline', verbose_name='Дисциплина'),
        ),
    ]
