# Generated by Django 3.2.8 on 2021-12-01 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0008_alter_skydiverrequest_discipline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skydiverrequest',
            name='services',
        ),
        migrations.CreateModel(
            name='RequestService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manifest.skydiverrequest')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='manifest.skydivingservice')),
            ],
        ),
    ]
