# Generated by Django 3.2.8 on 2021-12-02 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0009_auto_20211201_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestservice',
            options={'verbose_name': 'Услуга в заявке', 'verbose_name_plural': 'Услуги в заявке'},
        ),
        migrations.RenameField(
            model_name='planelift',
            old_name='ord_numver',
            new_name='ord_number',
        ),
        migrations.AlterField(
            model_name='balanceoperation',
            name='operation_type',
            field=models.CharField(choices=[('WD', 'Cписание'), ('RF', 'Зачисление')], max_length=2, verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='giftcertificate',
            name='status',
            field=models.CharField(choices=[('IS', 'Выпущен'), ('BO', 'Приобретен'), ('US', 'Использован')], max_length=2, verbose_name='Текущий статус сертификата'),
        ),
        migrations.AlterField(
            model_name='planelift',
            name='status',
            field=models.CharField(choices=[('CR', 'Создан'), ('PL', 'Запланирован'), ('FRM', 'Сформирован'), ('RD', 'Готов к взлету'), ('IP', 'В воздухе'), ('CMP', 'Завершен'), ('CNC', 'Отменен')], max_length=3, verbose_name='Текущий статус подъема'),
        ),
        migrations.AlterField(
            model_name='requestservice',
            name='quantity',
            field=models.FloatField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='requestservice',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manifest.skydiverrequest', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='requestservice',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='manifest.skydivingservice', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='skydiverrequest',
            name='status',
            field=models.CharField(choices=[('CR', 'Создана'), ('MNF', 'Включена в подъем'), ('CMP', 'Выполнена')], max_length=3, verbose_name='Текущий статус заявки'),
        ),
    ]
